global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
  - job_name: 'db'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']    
  - job_name: 'flowise-v1-metrics'
    static_configs:
      - targets: ['flowise:3000']
    metrics_path: /api/v1/metrics
    scheme: http
  - job_name: 'server'
    static_configs:
      - targets: ['172.18.0.1:9100']



      